package me.artspb.cts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-02-02T17:39:35.466+04:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://artspb.me/cts", name = "CurrentTimeService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CurrentTimeService {

    @WebResult(name = "currentTime", targetNamespace = "http://artspb.me/cts", partName = "currentTime")
    @WebMethod(action = "http://artspb.me/cts")
    public javax.xml.datatype.XMLGregorianCalendar getCurrentTime(
        @WebParam(partName = "timeZoneId", name = "timeZoneId", targetNamespace = "http://artspb.me/cts")
        java.lang.String timeZoneId
    );
}
